# Generated by Django 5.0.1 on 2024-01-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.product'),
        ),
    ]
