# Generated by Django 5.0.1 on 2024-01-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_status_productstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productstatus', to='product.product'),
        ),
    ]
